spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,refresh,loggers,logfile,hystrix.stream,activiti,turbine.stream

spring.boot.admin.turbine:
  clusters: default
  location: admin

turbine:
  appConfig: discovery, customer, catalog, order
  clusterNameExpression: "'default'"
  instanceUrlSuffix:
    default: /private/hystrix.stream